name: ER Stagesupport
favicon: null
layout_spectrum: 1
typography_spectrum: 0.07149
title: erstagesupport.eu
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffe500'
    - '#000000'
    - '#ffffff'
    - '#ff0000'
    - '#ff5500'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
