name: ER Stagesupport
favicon: null
layout_spectrum: 0.5737613346427679
typography_spectrum: 0.531452224124223
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3159438888542354
  lightness: 0.19605073821730912
  saturation: 0.4169499285053462
  rhythmicContrast: 0.9164292381610721
purpose: []
